// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Introdução',
      link: {
        type: 'doc',
        id: 'introduction/beginning'
      },
      items: [
        {
          type: 'category',
          label: 'Assembly',
          link: {
            type: 'doc',
            id: 'introduction/assembly/assembly'
          },
          items: [
            'introduction/assembly/2-2-stack',
            'introduction/assembly/2-3-assembly-pratica',
            'introduction/assembly/2-1-coding-assembly'
          ],
        },
        'introduction/endianness',
        'introduction/ghidra',
        'introduction/gdb',
        'introduction/pwntools',
      ],
    },
    {
      type: 'category',
      label: 'Pwning',
      link: {
        type: 'doc',
        id: 'pwning/beginning'
      },
      items: [
        'pwning/1-1-protections',
        {
          type: 'category',
          label: 'Stack',
          link: {
            type: 'doc',
            id: 'pwning/stack/intro'
          },
          items: [
            {
              type: 'category',
              label: 'Buffer Overflow',
              link: {
                type: 'doc',
                id: 'pwning/stack/bof/2-0-bof'
              },
              items: [
                'pwning/stack/bof/2-1-bof-variables',
                'pwning/stack/bof/2-2-bof-callfunction',
                'pwning/stack/bof/2-3-bof-shellcode',
                'pwning/stack/bof/debruijn',
              ],
            },
            'pwning/stack/format-strings',
            {
              type: 'category',
              label: 'ROP (Return-Oriented Programming)',
              link: {
                type: 'doc',
                id: 'pwning/stack/rop/8-1-rop'
              },
              items: [
                'pwning/stack/rop/8-2-partial-overwrite',
                'pwning/stack/rop/8-3-stack-pivoting',
                'pwning/stack/rop/8-4-sigrop',
                'pwning/stack/rop/8-5-ret2libc'
              ],
            },
            'pwning/stack/got'
          ],
        },
        {
          type: 'category',
          label: 'Heap',
          link: {
            type: 'doc',
            id: 'pwning/heap/heap'
          },
          items: [
            'pwning/heap/uaf',
            'pwning/heap/malloc_consolidate',
            'pwning/heap/double-free'
          ],
        },
        {
          type: 'category',
          label: 'Outros',
          link: {
            type: 'doc',
            id: 'pwning/others/intro'
          },
          items: [
            'pwning/others/array-indexing',
            'pwning/others/integer-overflow',
            'pwning/others/bad-seed',
            'pwning/others/z3',
          ],
        }
      ],
    },
    /* Fast Food */
    {
      type: 'category',
      label: 'Fast Food',
      link: {
        type: 'doc',
        id: 'fast-food/beginning'
      },
      items: [
        {
          type: 'category',
          label: 'Introdução',
          items: [
            'fast-food/introduction/assembly',
            'fast-food/introduction/endianness',
            'fast-food/introduction/ghidra',
            'fast-food/introduction/gdb',
            'fast-food/introduction/pwntools'
          ]
        },
        {
          type: 'category',
          label: 'Pwning',
          items: [
            'fast-food/pwning/beginning',
            'fast-food/pwning/bof',
            'fast-food/pwning/bof-callfunction',
            'fast-food/pwning/bof-shellcode'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Material extra',
      link: {
        type: 'doc',
        id: 'extra/intro'
      },
      items: [
        'extra/syscall-tb',
        'extra/shellcraft-li',
        'extra/call-convention'
      ],
    },
  ],
   
};

export default sidebars;