// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Introdução',
      link: {
        type: 'doc',
        id: 'introduction/beginning'
      },
      items: [
        'introduction/assembly',
        'introduction/endianness',
        'introduction/ghidra',
        'introduction/gdb',
        'introduction/pwntools',
      ],
    },
    {
      type: 'category',
      label: 'Pwning',
      link: {
        type: 'doc',
        id: 'pwning/beginning'
      },
      items: [
        'pwning/1-1-protections',
        {
          type: 'category',
          label: 'Buffer Overflow',
          link: {
            type: 'doc',
            id: 'pwning/bof/2-0-bof'
          },
          items: [
            'pwning/bof/2-1-bof-variables',
            'pwning/bof/2-2-bof-callfunction',
            'pwning/bof/2-3-bof-shellcode',
          ],
        },
        'pwning/format-strings',
        'pwning/array-indexing',
        'pwning/integer-overflow',
        'pwning/bad-seed',
        'pwning/z3',
        {
          type: 'category',
          label: 'ROP (Return-Oriented Programming)',
          link: {
            type: 'doc',
            id: 'pwning/rop/8-1-rop'
          },
          items: [
            'pwning/rop/8-2-partial-overwrite',
          ],
        },
      ],
    },
    /* Fast Food */
    {
      type: 'category',
      label: 'Fast Food',
      link: {
        type: 'doc',
        id: 'fast-food/beginning'
      },
      items: [
        {
          type: 'category',
          label: 'Introdução',
          items: [
            'fast-food/introduction/assembly',
            'fast-food/introduction/endianness',
            'fast-food/introduction/ghidra',
            'fast-food/introduction/gdb',
            'fast-food/introduction/pwntools'
          ]
        },
        {
          type: 'category',
          label: 'Pwning',
          items: [
            'fast-food/pwning/beginning',
            'fast-food/pwning/bof',
            'fast-food/pwning/bof-callfunction',
            'fast-food/pwning/bof-shellcode'
          ]
        }
      ]
    }
  ],
   
};

export default sidebars;
